language: go

go:
  - 1.13.x

env:
  - GO111MODULE=on

git:
  depth: 1

go_import_path: code.cloudfoundry.org/eirini-staging

# Install dependencies responsible for testing/linting
before_install:
    - go get -u github.com/onsi/ginkgo/ginkgo
    - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $GOPATH/bin

# Skip install step; use vendored dependencies
install: true

script:
  - golangci-lint run
  - ./scripts/test.sh
